### ISSUE TITLE
Error getting a directory

### ISSUE THREAD

**Issue by olizilla** [olizilla/ipfs-get#1]
```console
$ ipfs-get QmTnuLaivKc1Aj8LBf2iWBHDXsmedip3zSPbQcGi6BFwTC                                                                                                                  
📡 Fetching .car file from http://127.0.0.1:5001/
Error: "codec" property is deprecated, use integer "code" property instead
    at CID.get codec [as codec] (file:///Users/oli/Code/olizilla/ipfs-get/node_modules/multiformats/esm/src/cid.js:92:11)
    at resolve (/Users/oli/Code/olizilla/ipfs-get/node_modules/ipfs-unixfs-exporter/src/resolvers/index.js:28:34)
    at Object.yieldDirectoryContent [as content] (/Users/oli/Code/olizilla/ipfs-get/node_modules/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/directory.js:23:28)
    at yieldDirectoryContent.next (<anonymous>)
    at recurse (/Users/oli/Code/olizilla/ipfs-get/node_modules/ipfs-unixfs-exporter/src/index.js:141:22)
    at recurse.next (<anonymous>)
    at Object.recursive (/Users/oli/Code/olizilla/ipfs-get/node_modules/ipfs-unixfs-exporter/src/index.js:130:22)
    at recursive.next (<anonymous>)
    at extractCar (file:///Users/oli/Code/olizilla/ipfs-get/index.js:72:20)
    at async ipfsGet (file:///Users/oli/Code/olizilla/ipfs-get/index.js:63:3)
```

**Comment by olizilla** [comment]
Fixed via @achingbrain by depending on the bleeding edge unixfs-exporter with all nu-multiformats in https://github.com/ipfs/js-ipfs-unixfs/pull/116

**Comment by olizilla** [comment]
see: https://github.com/olizilla/ipfs-get/commit/416a1b77f3a56b9ab65889f890c5504a6b714c45#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R22
